FROM python:3.11-slim

# Установка ffmpeg
RUN apt-get update && \
    apt-get install -y ffmpeg && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем проект
COPY . .

# Render сам пробрасывает PORT, EXPOSE можно не указывать, но оставим для читаемости
EXPOSE 5000

# Запуск Gunicorn c таймаутом 300 сек
CMD gunicorn main:app --bind 0.0.0.0:$PORT --timeout 300
